from pydantic import BaseModel, Field
from datetime import datetime
from typing import List


class ComponentScores(BaseModel):
    """
    Represents the breakdown of health scores across different portfolio metrics.

    Each score rates a specific dimension of portfolio health on a 0.0 - 100.0 scale.
    Higher is always better.

    Attributes:
        diversification_score: Number of holdings — more holdings = less unsystematic risk.
        concentration_score:   Max single stock weight — lower concentration = higher score.
        sector_score:          Max single sector weight — lower sector concentration = higher score.
        beta_score:            Distance of portfolio beta from 1.0 — closer to 1.0 = higher score.
        volatility_score:      Annualised portfolio volatility — lower volatility = higher score.
    """
    diversification_score: float = 0.0
    concentration_score: float = 0.0
    sector_score: float = 0.0
    beta_score: float = 0.0
    volatility_score: float = 0.0

    class Config:
        from_attributes = True


class HealthRecommendation(BaseModel):
    """
    Represents a single actionable recommendation generated by the ExplainabilityService.

    Attributes:
        priority: Urgency level — "high", "medium", or "low".
        title:    Short label shown in the UI card header.
        detail:   Context line showing current score (e.g. "Current score: 23.4/100").
        action:   Specific step the investor should take — plain English, no jargon.
    """
    priority: str
    title: str
    detail: str
    action: str

    class Config:
        from_attributes = True


class PortfolioHealthResponse(BaseModel):
    """
    Full health evaluation response returned by GET /api/health/portfolio/{id}/health.

    Produced by HealthEngineService.evaluate() which orchestrates:
    1. HealthEngineService      → calculates component scores and weighted health score
    2. ExplainabilityService    → interprets scores into strengths, weaknesses, recommendations

    Attributes:
        portfolio_id:      The portfolio being evaluated.
        health_score:      Composite weighted score 0-100.
        grade:             Letter grade A/B/C/D/F derived from health_score.
        component_scores:  Individual scores for each of the 5 health dimensions.
        strengths:         Human-readable statements about what the portfolio does well.
        weaknesses:        Human-readable statements about portfolio vulnerabilities.
        recommendations:   Prioritised actionable steps — high priority first.
        computed_at:       UTC timestamp of evaluation.
        holdings_count:    Number of unique holdings in the portfolio.
        total_invested:    Sum of quantity * buy_price across all holdings in rupees.
    """
    portfolio_id: int
    health_score: float = 0.0
    grade: str = "N/A"
    component_scores: ComponentScores = Field(default_factory=ComponentScores)
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    recommendations: List[HealthRecommendation] = Field(default_factory=list)
    computed_at: datetime = Field(default_factory=datetime.utcnow)
    holdings_count: int = 0
    total_invested: float = 0.0

    class Config:
        from_attributes = True